apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulk-pack-transformer-v2
  labels:
    app: bulk-pack-transformer-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bulk-pack-transformer-v2
  template:
    metadata:
      labels:
        app: bulk-pack-transformer-v2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: doks.digitalocean.com/node-pool
                    operator: In
                    values:
                      - microservices-node-pool
      containers:
        - name: bulk-pack-transformer-v2
          image: greenstand/bulk-pack-transformer-v2:TAG
          ports:
            - containerPort: 80
          env:
            - name: TREETRACKER_FIELD_DATA_URL
              value: http://treetracker-field-data.field-data-api
            - name: TREETRACKER_API_URL
              value: http://treetracker-api.treetracker-api
            - name: TREETRACKER_MESSAGING_API_URL
              value: http://treetracker-messaging-api.messaging-api
