apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: greenstand-docker-secret
  namespace: bulk-pack-services
spec:
  encryptedData:
    '.dockerconfigjson': sealedSecret
  template:
    metadata:
      name: greenstand-docker-secret
      namespace: bulk-pack-services
    type: kubernetes.io/dockerconfigjson
