apiVersion: v1
kind: Service
metadata:
  name: bulk-pack-transformer-v2
spec:
  selector:
    app: bulk-pack-transformer-v2
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3006
